Карта для путешествий: "{name}, в июне у вас траты на такси {taxi_sum}. С тревел-картой часть расходов вернулась бы кешбэком ≈{benefit}. Открыть карту."
Премиальная карта: "{name}, у вас траты в ресторанах {rest_sum}. Премиальная карта даст повышенный кешбэк и бесплатные снятия. Подключите сейчас."
Кредитная карта: "{name}, ваши топ-категории — {cat1}, {cat2}, {cat3}. Кредитная карта даёт до 10% в любимых категориях. Оформить карту."
Обмен валют: "{name}, вы часто платите в валюте. В приложении выгодный обмен и авто-покупка по целевому курсу. Настроить обмен."
Кредит наличными: "{name}, если нужен запас на крупные траты — можно оформить кредит наличными. Узнать доступный лимит."
Депозит мультивалютный: "{name}, у вас остаются свободные средства. Разместите их на мультивалютном вкладе. Открыть вклад."
Депозит сберегательный: "{name}, у вас стабильный остаток. Разместите средства на сберегательном вкладе с повышенной ставкой. Открыть вклад."
Депозит накопительный: "{name}, хотите копить с удобными пополнениями? Накопительный вклад поможет. Открыть вклад."
Инвестиции (брокерский счёт): "{name}, попробуйте инвестиции с низким порогом входа. Открыть счёт."
Золотые слитки: "{name}, защитите сбережения — золото может помочь в диверсификации. Посмотреть варианты."
